language: node_js
node_js: '10'
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - FORCE_COLOR=1
install:
  - yarn --frozen-lockfile
jobs:
  include:
    - stage: test
      script:
        - yarn run prettier
        - yarn run tslint
        - yarn run build
        - yarn test
        - nyc report --reporter json
        - 'bash <(curl -s https://codecov.io/bash)'
stages:
  - test
branches:
  only:
    - master
    - /^renovate\//
